import json
from pathlib import Path

NOTEBOOK_PATH = Path('Speech_Classification_Swahili.ipynb')


def create_markdown_cell(text: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in text.split("\n")]
    }


def main():
    if not NOTEBOOK_PATH.exists():
        raise FileNotFoundError(f"Notebook not found: {NOTEBOOK_PATH}")

    nb = json.loads(NOTEBOOK_PATH.read_text(encoding='utf-8'))
    cells = nb.get('cells', [])

    # Avoid duplicate insertion by checking for our marker
    marker = "<!-- auto:results_visualizations -->"
    if any(marker in ''.join(c.get('source', '')) for c in cells if c.get('cell_type') == 'markdown'):
        print("Notebook already contains auto-inserted results section; updating skipped.")
        return

    # Header and context
    header_md = (
        "# Results Visualizations\n\n"
        f"{marker}\n"
        "This section presents key visuals generated by the runner pipeline.\n"
        "Images are sized and captioned consistently for clarity.\n"
    )
    cells.append(create_markdown_cell(header_md))

    # Build figure blocks
    figures = [
        {
            "title": "Model Comparison",
            "file": Path('results/figures/model_comparison.png'),
            "caption": "Accuracy and training time across models"
        },
        {
            "title": "Confusion Matrix (Random Forest)",
            "file": Path('results/figures/confusion_matrix_random_forest.png'),
            "caption": "Confusion matrix for Random Forest"
        },
        {
            "title": "Confusion Matrix (SVM)",
            "file": Path('results/figures/confusion_matrix_svm.png'),
            "caption": "Confusion matrix for SVM"
        },
    ]

    for fig in figures:
        exists = fig["file"].exists()
        img_rel = str(fig["file"]).replace('\\', '/')
        md = [
            f"## {fig['title']}",
            "",
            "<figure style=\"text-align:center;\">",
            f"  <img src=\"{img_rel}\" alt=\"{fig['title']}\" width=\"900\">" if exists else f"  <div style=\"color:#b00;\">[Image not found: {img_rel}]</div>",
            f"  <figcaption style=\"font-size:14px; color:#555;\">{fig['caption']}</figcaption>",
            "</figure>",
            ""
        ]
        cells.append(create_markdown_cell("\n".join(md)))

    # Attribution & Licensing
    license_md = (
        "## Attribution & Licensing\n\n"
        "- Figures are generated by this project’s code and experiments.\n"
        "- Dataset: Mozilla Common Voice (Swahili) — Clips licensed CC0 1.0.\n"
        "- No external stock images used; attribution not required beyond dataset.\n"
    )
    cells.append(create_markdown_cell(license_md))

    # Update notebook and write back
    nb['cells'] = cells
    NOTEBOOK_PATH.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding='utf-8')
    print(f"Updated notebook: {NOTEBOOK_PATH}")


if __name__ == '__main__':
    main()